### PR TITLE
cartridge: fix verification of checksums for cartridge and bootrom

### PR DESCRIPTION
**Pull request by while-loop**
In the attempt to get the emulator running on OSX, I thought I would send the PR for some tests and fixes.

The bootrom nintendo logo had an incorrect offset so roms were failing verification.

I also added tests for parsing cartridges.

### CODE REVIEW

**Comment by pmcanseco** [comment]
hey there! thanks so much for submitting a pull request :D 

It does look like I had a mistake on those logo offsets. What roms did you try, and were you able to get them running with your changes?

it looks like everything about it is in order, and [travis-ci seems to agree](https://travis-ci.org/pmcanseco/java-gb/builds/390976107). I plan to do a couple more tests when I get home from work and provided everything checks out, it should be merged tonight.

Thanks again! 

Pablo

**Comment by while-loop** [comment]
I wasn't able to get any of the provided games working on macOS (the game windows is just white.. not sure where the problem is yet).

On Ubuntu I'm able to play drmario, tetris, and cpu_instrs with the new changes. 
Pokemon doesn't get past the start menu on your master or my branch.

**Comment by pmcanseco** [comment]
Were you getting any crazy errors when you were running on OS X? Prior to merging, I'm able to play Mario, Tetris, and Dr. Mario on Windows and Ubuntu. I don't have an OS X machine to test on :/ Pokemon Blue is not expected to get past the start screen.

Also, it doesn't look like there's any changes to the functionality of the emulator in here. 

image

As in the screenshot above, the only usage of the `MemoryManager.getBiosLogo()` function is in the Cartridge class, where the checksum is just computed and then we print if it checks out or not. It wouldn't cause any hanging in Tetris, Dr. Mario, or Super Mario Land because the emulator ignores it completely and does its own checking as part of the bootrom sequence.

Also, where did the 168 number from `MemoryManager.java line 30` come from? The [gameboy documentation](http://gbdev.gg8.se/wiki/articles/The_Cartridge_Header) states that the logo starts at hex 104 and ends at hex 133, so if anything 104 should be changed to 0x104 or decimal 260.

I'm not trying to be discouraging, I'm just trying to make sure I understand what's going on. Please tell me if I'm missing something :)

Also, I remember you from senior design. Hope all went well for your project :)

Pablo

**Comment by while-loop** [comment]
> Also, I remember you from senior design. Hope all went well for your project :)

All did go well for my project 😄. Thanks for asking

> I'm not trying to be discouraging, I'm just trying to make sure I understand what's going on. Please tell me if I'm missing something :)

No worries!! I didn't see it as discouraging, you need to also know what is being merged into your repo 😁.

> Also, where did the 168 number from MemoryManager.java line 30 come from? The gameboy documentation states that the logo starts at hex 104 and ends at hex 133, so if anything 104 should be changed to 0x104 or decimal 260.

As for the offset, I got `168 (Addr_00A8)` from the [bootstrap rom](http://gbdev.gg8.se/wiki/articles/Gameboy_Bootstrap_ROM#Contents_of_the_ROM) specs, not the cartridge ROM. 



For the macOS problems, I'll open a separate issue and provide info there.

**Comment by pmcanseco** [comment]
Yup, the logo is in a different spot in the bootrom than where it is in the cartridge header. Great catch. Merging.

**Pull request merged**
